services:
  - type: web
    name: navidrome
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ND_DATAFOLDER
        value: /data
      - key: ND_MUSICFOLDER
        value: /music
      - key: RCLONE_CONFIG_ONEDRIVE_TYPE
        value: onedrive
      - key: RCLONE_CONFIG_ONEDRIVE_TOKEN
        sync: false   # we'll add manually in Render dashboard
      - key: RCLONE_CONFIG_ONEDRIVE_DRIVE_ID
        sync: false
      - key: RCLONE_CONFIG_ONEDRIVE_DRIVE_TYPE
        value: personal
